### ISSUE TITLE
0xbranded - DoS of LP Withdrawals Due to Abuse of `unlocked_reserves`

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-velar-artha-judging#28]
0xbranded

High

# DoS of LP Withdrawals Due to Abuse of `unlocked_reserves`

## Summary
LP withdrawals can be blocked by a malicious actor inflating the OI to intentionally increase `unlocked_reserves`.

## Vulnerability Detail
The protocol locks user deposits in order to ensure future payout obligations can be met, a key functionality outlined in the comment specifications. The `pool.vy` function [`unlocked_reserves`](https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/pools.vy#L125-L130) reports the token reserves not currently tied up to fulfill future payouts:

```vyper
def unlocked_reserves(id: uint256) -> Tokens:
  ps: PoolState = Pools(self).lookup(id)
  return Tokens({
    base : ps.base_reserves  - ps.base_interest,
    quote: ps.quote_reserves - ps.quote_interest,
  })
```

This function is mentioned in [`calc_burn`](https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/pools.vy#L216-L222) which is called when LPs are making a withdrawal:

```vyper
  unlocked: Tokens  = Pools(self).unlocked_reserves(id)
  ...
  assert uv         >= bv,             ERR_PRECONDITIONS
  assert amts.base  <= unlocked.base,  ERR_PRECONDITIONS
  assert amts.quote <= unlocked.quote, ERR_PRECONDITIONS
```

Additionally, after every user action in `core.vy` (including burn and open) an [invariants](https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/core.vy#L126-L133) check is performed with similar enforcement:

```vyper
def INVARIANTS(id: uint256, base_token: address, quote_token: address):
  pool         : PoolState = self.POOLS.lookup(id)
...
  assert pool.base_reserves  >= pool.base_interest,  ERR_INVARIANTS
  assert pool.quote_reserves >= pool.quote_interest, ERR_INVARIANTS
```

Critically, the same comparison between `interest` and `reserves` is being made in both cases. Since `open` increases the `interest`, a malicious attacker can take out positions with large enough size and leverage to decrease `unlocked_reserves` to an arbitrarily small value.

As long as he is well-capitalized, he can take out equal notional size positions on both the long and short side, eliminating price fluctuations and funding payments from the cost of this attack, and locking both quote and base reserves. While he would still pay borrowing rates, as well as the initial cost of opening a position, these costs are low enough to enable him to maintain this DoS (assuming he manages his position periodically to avoid liquidation).

## Impact
With a large enough bankroll, all withdrawals can be blocked for several months at a nominal cost to the attacker. Anytime the unlocked reserves grows as a result of user actions (eg. mint, close), he can simply open more positions to extend the attack.

Withdrawals can very easily be blocked for a period of 4 hours (DoS period mentioned in the [contest rules](https://audits.sherlock.xyz/contests/526)) with a much more modest bankroll and cost of attack.

Opening new positions will also be blocked, but the blocking of withdrawals is much more problematic as this is a time-sensitive operation given fluctuating crypto prices and user liquidity needs (especially if the attack is carried out for the long durations described). This would significantly erode trust in the protocol and discourage future depositors, even after the attack has concluded.

## Tool used

Manual Review

## Recommendation
Specifically for the opening of positions, enforce a lower limit of accessible reserves in order to facilitate withdrawals even when positions can no longer be opened.

For example at the end of opening a position, consider asserting:
```vyper
  assert pool.base_reserves  >= 2*pool.base_interest,  ERR_INVARIANTS
  assert pool.quote_reserves >= 2*pool.quote_interest, ERR_INVARIANTS
```

**Comment by spacegliderrrr** [comment]
Escalate

Issue should be low/info. Ultimately, all LPs would want is fees and this would give them the highest fees possible. Furthermore, the attack is extremely costly, as it would require user to lock up hundreds of thousands/ millions, losing a significant % of them. Any user would have an incentive to add liquidity at extremely high APY, which would allow for both new positions opens and LP withdraws.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Issue should be low/info. Ultimately, all LPs would want is fees and this would give them the highest fees possible. Furthermore, the attack is extremely costly, as it would require user to lock up hundreds of thousands/ millions, losing a significant % of them. Any user would have an incentive to add liquidity at extremely high APY, which would allow for both new positions opens and LP withdraws.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by msheikhattari** [comment]
This attack can be performed at a low cost for a few reasons:
1. The attacker is presumably not the only position in the pool, and only needs to push locked reserves up the remainder of the way to block withdrawals
2. Using high leverage, a small amount of collateral can be posted. While the borrow rates do go up, the fees are assessed on the collateral of each position only. Thus the increased cost is largely socialized among all positions.

The DoS timespan has been overrided to 4 hr as per the contest guidelines. Given the above mentioned factors, it is trivial for an attacker to lock withdrawals for this period of time.

Moreoever, this locks a time sensitive functionality as it pertains to withdrawals, so I would further escalate this to a high severity.

**Comment by WangSecurity** [comment]
About the 2 reasons above:
1. But in that case, the other users can close their positions which would free the unlocked_reserves to some extent.
2. This is also very risky and can lead to the attacker being liquidated due to price fluctuations.

Hence, I think the attacker still has to have mid to high capital. Also, I agree that the constraints are very high and there are several factors that could resolve that DOS state. But, since the DOS window has been decreased to 4 hours, I think this issue indeed can block the functionality for 4 hours. Hence, medium severity is appropriate. Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
UPD:

It was flagged that this issue is actually a known one from the [previous audit](https://github.com/Thesis-Defense/Security-Audit-Reports/blob/main/PDFs/240717_Thesis_Defense-Velar_Vyper_Smart_Contracts_Security_Audit_Report.pdf) (see issue `#8`). Yes, the issue is not very well described there, but it identifies that the LPs cannot withdraw if there are not enough `unlocked_reserves`. Hence, this should be invalid as a known issue. Planning to reject the escalation and leave the issue as it is.

**Comment by msheikhattari** [comment]
While I agree that the locking of reserves is a defined feature of the pool, the issue defined here describes an invalidation of those assumptions. A malicious user can abuse this feature to explicitly lock all withdrawals from the pool. 

Locking of reserves is a design feature that can still be maintained while preventing this path of attack from occurring. The issue reported in that previous audit does not make this distinction nor identify the path of attack outlined here, it merely takes contention with that design choice.

Given that it meets both criteria (locking of funds, impacted availability of time-sensitive functions) for DoS I believe this issue should still be considered as a valid high severity finding.

**Comment by WangSecurity** [comment]
But, the reason why it's a known issue is not because of the impact, but because of the root cause. The issue in the previous audit report identifies that the LPs cannot withdraw when there are not enough unlocked reserves, which we can see in the Description:
> The protocol can **prevent liquidity providers from withdrawing their liquidity from the pool** on demand until an unspecified time **if there is not enough unlocked reserves in the pool**.

And in the Impact:
> The protocol **prevents liquidity providers from withdrawing liquidity when expected**.

I see that the report from the previous audit doesn't identify the attack, where a malicious actor could intentionally keep `unlocked_reserves` low (or 0), but, unfortunately, it's not enough grounds to say it's an unknown issue.

Hence, the decision remains the same, accept the escalation and leave the issue as it is.

**Comment by msheikhattari** [comment]
This issue specifically points out that the locking of reserves should not follow the same ratio between positions and LPs. Reserves can still be locked for LPs, but assessing the same required ratio for both opens it up to a unique risk. 

The suggestion isn't a design change or contention with locking of reserves. It's that open positions provide a direct lever for attackers to block withdrawals. 

This can be addressed by assessing a different percentage of available reserves for positions to be opened than the total unlocked reserves. For example positions have access to 70% of the full available reserves, so they cannot arbitrarily DoS withdrawals by maxing out their available reserves. 

That prior reported issue describes an intended design of the protocol- locking of reserves preventing withdrawals. This issue challenges the assumptions made, particularly how the current _implementation_ of that design choice is problematic, along with suggestions that would keep the design in place while mitigating this unaccounted for attack vector.

**Comment by WangSecurity** [comment]
I'm not trying to claim that this issue is a design recommendation. What I'm trying to say is that it's known that the LP cannot withdraw when there are little to no `unlocked_reserves`, which is ultimately the root cause of this issue. Hence, it should be invalid as a known issue, planning to accept the escalation and invalidate the issue.

**Comment by msheikhattari** [comment]
The root cause of this issue is specifically that LPs and positions have the same enforced `unlocked_reserves` requirement. Indeed it is a known issue that withdrawals will be prevented when there are insufficient `unlocked_reserves`, but this issue is pointing out the dangers that both parties interface with the same reserve rate, and the ease of abuse that can result. 

In particular, this issue can be addressed by assessing a different reserve requirement on LPs than on borrowers.

**Comment by WangSecurity** [comment]
Still, the issues have the same root cause, and as we can see in the Audit report, it is also the design to not allow withdrawals in this scenario. I agree that this report identifies a more severe case, but it doesn't change the fact that the root mistake is the same as in the identified audit report. Hence, this issue is known and should be invalid. Planning to accept the escalation and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [spacegliderrrr](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/28/#issuecomment-2344387728): accepted
