### ISSUE TITLE
storm0x - Integration of BridgeUSDC may lead to some positions not able to be liquidated properly

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-velar-artha-judging#48]
storm0x

High

# Integration of BridgeUSDC may lead to some positions not able to be liquidated properly

high

# Integration of BridgeUSDC may lead to some positions not able to be liquidated properly

## Summary

Liquidations are an important part of the protocol invariants, it is crucial that they work correctly for all cases and in a timely manner to avoid bad debt.

In the protocol there are both base and quote tokens, initially is intended to use a tokenized
BTC as the base token and a bridged USDT version as the quote token in the BOB network.

The other major stablecoin in the BOB network for integration is USDC.

USDC is a bridged token in the BOB network with growing supply, and as is common for the USDC implementation to contain blacklist functionality which can revert some transfers.

Liquidations require transfers to work properly for sending remainder to the user and the liquidator, this can be a problem if the user opened one or more positions in a pool integrating USDC and later that user gets blacklisted in the USDC contract.

The user positions will revert on liquidation unable to close the positions in a timely manner which could put the protocol at risk of accruing bad debt.

## Vulnerability Detail

These are the addresses for Bridged USDC in the BOB network

Proxy
https://explorer.gobob.xyz/token/0xe75D0fB2C24A55cA1e3F96781a2bCC7bdba058F0?tab=contract
Implementation
https://explorer.gobob.xyz/address/0x27d58e4510a3963abc70bce554aeac60846998ab?tab=contract

The transfer method in the USDC contract has a check for blacklisted users that can revert the transfer.

```solidity
function transfer(address to, uint256 value)
        external
        override
        whenNotPaused
        notBlacklisted(msg.sender)
        notBlacklisted(to) <-- This is the check that can revert the transfer
        returns (bool)
    {
        _transfer(msg.sender, to, value);
        return true;
    }
```

In the liquidation logic as part of the accounting, the fees are sent to the liquidator and any remaining balance of both base and quote token is sent back to the owner of the position.

https://github.com/sherlock-audit/2024-08-velar-artha/blob/18ef2d8dc0162aca79bd71710f08a3c18c94a36e/gl-sherlock/contracts/core.vy#L343

If the user is blacklisted in the USDC contract the transfer will revert and the liquidation will fail.

## Impact

Liquidations will fail to work properly and in a timely manner if a user with several open positions is later blacklisted in the USDC contract.

This could lead to bad debt in the protocol and a risk of insolvency since the calculations for when a position is liquidatable are based on the current state of the position and price, if there is a big price fluctuation the position will fail liquidation until the position remaining for the user reaches 0, which could have consequences for the liquidation fee also being 0 and liquidators not being incentivized to liquidate the position.

Furthermore, the position could reach such bad state that by the time the position is able to be liquidated the invariants check may fail further reverting the liquidation.

## Code Snippet

```vyper
@external
def liquidate(
  id         : uint256,
  base_token : address,
  quote_token: address,
  position_id: uint256,
  ctx        : Ctx) -> PositionValue:
 ...

  # important that all these transfers never revert
  if base_amt_final.fee > 0:
    assert ERC20(base_token).transfer(user, base_amt_final.fee, default_return_value=True), "ERR_ERC20"
  if quote_amt_final.fee > 0:
    assert ERC20(quote_token).transfer(user, quote_amt_final.fee, default_return_value=True), "ERR_ERC20"
  if base_amt_final.remaining > 0:
    assert ERC20(base_token).transfer(position.user, base_amt_final.remaining, default_return_value=True), "ERR_ERC20"
  if quote_amt_final.remaining > 0:
    assert ERC20(quote_token).transfer(position.user, quote_amt_final.remaining, default_return_value=True), "ERR_ERC20" <-- important that these transfers never revert

  self.INVARIANTS(id, base_token, quote_token)

  log Liquidate(user, ctx, pool, value)
  return value
```

## Tool used

Manual Review

## Recommendation

Consider carefully which tokens to integrate on POOLS specifically on tokens that can be upgraded or blacklisted that could affect the liquidation process.

**Comment by 0xstormblessed** [comment]
Escalate 

according to this issue https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/110

this should also be valid, since i used a specific USDC token example that implements blacklist and its a potential quote token

**Comment by sherlock-admin3** [comment]
> Escalate 
> 
> according to this issue https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/110
> 
> this should also be valid, since i used a specific USDC token example that implements blacklist and its a potential quote token

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by spacegliderrrr** [comment]
Escalate

on behalf of submitter

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> on behalf of submitter

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by iamandreiski** [comment]
Adding to the escalation that #64 also refers to this issue and mentions USDC as a token that can interrupt liquidations.

**Comment by WangSecurity** [comment]
USDC is out of scope. The only tokens in scope are standard tokens and USDT (which doesn't have a blacklist mechanism on Bob). Hence, this issue is invalid. Planning to reject the escalation and leave the issue as it is.

**Comment by iamandreiski** [comment]
Hey @WangSecurity thank you for the judging efforts.
First and foremost, according to judging roles commit [e7dc892](https://github.com/sherlock-protocol/sherlock-v2-docs/blob/e7dc89270b05f8d2fcee69dc4204c7a2b8fb4cf9/audits/judging/judging/README.md) which is valid for this contest which is valid for this contest:

"Hierarchy of truth: If the protocol team provides no specific information, the default rules apply (judging guidelines).

If the protocol team provides specific information in the README or CODE COMMENTS, that information stands above all judging rules. In case of contradictions between the README and CODE COMMENTS, the README is the chosen source of truth."

According to the README: 

"If you are integrating tokens, are you allowing only whitelisted tokens to work with the codebase or any complying with the standard? Are they assumed to have certain properties, e.g. be non-reentrant? Are there any types of [weird tokens](https://github.com/d-xo/weird-erc20) you want to integrate?

Only standard tokens (without weird traits) will be used."

According to this all non-weird tokens are applicable to this codebase. Since USDC in question, should be applicable here. 

Furthermore, according to the sponsor: 

"
the quote token is assumed to always be a stable coin. almost everything should just work for a eth/btc pair but i would re-review and test the codebase very carefully if i wanted such a pool
also only erc20 standard compliant tokens (which luckily everything on bob seems to be since they all just extend optimismbridgederc20 which is basically oz)
"

With all due respect, its nowhere specified that the only "quote" token used will be USDT, if USDC is involved (as per documentation).

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [spacegliderrrr](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/48/#issuecomment-2344620207): rejected
