### ISSUE TITLE
KupiaSec - Funding fees should be calculated based on position volumes rather than utilization ratio

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-velar-artha-judging#76]
KupiaSec

High

# Funding fees should be calculated based on position volumes rather than utilization ratio

## Summary
Funding fees for perp positions are calculated using utilization ratio of base/quote assets.
This calculation is invalid since the protocol allows imbalance between base/quote assets in the pool.

## Vulnerability Detail
In the protocol, funding fees are paid between long and shot perp traders.
The basic design is that at any moment, if long perp trades happen more than short perp trades, long position openers pay short position openers the funding fee, and vice versa. This funding fees provides stability of the protocol and prevents loss of LPs and the protocol.

However, the funding fee calculation is executed in improper way, as shown below:

```vyper
# How funding_long and funding_short are calculated

funding_long     : uint256 = self.funding_fee(
  borrowing_long, long_utilization,  short_utilization)
funding_short    : uint256 = self.funding_fee(
  borrowing_short, short_utilization,  long_utilization)

...

# funding_fee implementation

def funding_fee(base_fee: uint256, col1: uint256, col2: uint256) -> uint256:
  imb: uint256 = self.imbalance(col1, col2)
  if imb == 0: return 0
  else       : return self.check_fee(self.scale(base_fee, imb))
```

As shown in the code snippet, funding fees are calculated using long and short utilization of the pool.
Thus, if `long utilization > short utilization`, long position openers pay funding fees for short position openers, and vice versa.

The problem is that the protocol allows imbalance between base and quote assets in the pool, for example, assuming `1 BTC = 50,000 USDC`, the value of base/quote assets might be different like `1 BTC + 10,000 USDC`. So as a result, even though `long utilization > short utilization`, actual notional long position size can be smaller than notional short size.

This vulnerability can cause significant loss to LP providers and the overall protocol because of reverse party paying funding fees.

Here's the scenario that loss can happen because of this vulnerability.

- It's bullish time, and everyone believes that BTC price will go up.
- The pool contains 200 BTC($10m in value) + 1M USDC ($1M in value)
- Since people know that BTC prices will go up, relatively much people open long positions.
- Assuming, 100 BTC of notional size of long positions are open. ($5m in value)
- The short openers are the ones who are willing to take risk of BTC price goes up but getting funding fees which might profit them in the end.
- Assuming, 600k USDC of notional size of short positions are open. ($0.6m in value)
- At this moment, `long_utilization = 50, short_utilization = 60`, but in position values, long value = $5m, short value = $0.6m.
- As a result, short position openers pay funding fees to long position openers.

This logic allows more and more long position openers to open their positions and less incentivize short openers.
At the end, it incurs significant losses to LP providers and to the protocol.

## Impact
Loss for LP providers and the protocol.

## Code Snippet
https://github.com/sherlock-audit/2024-08-velar-artha/blob/18ef2d8dc0162aca79bd71710f08a3c18c94a36e/gl-sherlock/contracts/params.vy#L46-L49

## Tool used
Manual Review

## Recommendation
The funding fee calculation logic has to be modified so that it uses actual value of positions rather than the utilization ratio to determine which party pays the funding fees.

**Comment by KupiaSecAdmin** [comment]
Escalate

This issue deserves High.

**Comment by msheikhattari** [comment]
This is a design choice. The market will equilibriate since if fees are high positions will close and LPs will enter until rates balance out.

**Comment by KupiaSecAdmin** [comment]
> This is a design choice. The market will equilibriate since if fees are high positions will close and LPs will enter until rates balance out.

This design choice is absolutely dangerous as shown in the PoC above.
Also the statement about this can't be issue because the market will equilibrate because LPs close positions is not true.
It's only assumption, can't be a factor to invalidate this issue.

**Comment by msheikhattari** [comment]
Because of the nature of `calc_burn` it's also unlikely that the pool would ever become so imbalanced. It would require LPs to persistently provide liquidity in a single token, and for very few LPs to exit the pool for a long duration of time. 

The alternative choice of using position values across both sides of the pool has dangers as well and requires a total redesign of this facet of the protocol

**Comment by WangSecurity** [comment]
@KupiaSecAdmin, to clarify, long utilisation == 50 because 50% of the value is used for longs (i.e. 100 BTC out of 200)? Similarly to 600k USDC out of 1M USDC, that's why the short utilisation is 60, correct?

**Comment by KupiaSecAdmin** [comment]
@WangSecurity - Yes correct.

**Comment by pashap9990** [comment]
imo if pool reaches to that point[200BTC, 1M USDC] your issue is correct but we should think about this question, is it possible to reach that point? based on comments in code base,burn function tries to balance quote and base token in pool and might reach that point which has mentioned in issue can be hard
```
def balanced(state: Value, burn_value: uint256, ctx: Ctx) -> Tokens:
  """
  Given the current state of the pool reserves, returns a mix of tokens
  of total value burn_value which improves pool balance (we consider a
  pool balanced when te value of base reserves equals quote reserves).
  Note that if we have an imbalanced pool (which is not necessarily
  a bad thing), this means that LPs mostly get back the tokens they
  put in.
  The preconditions (burn_value <= reserves) for this must be
  checked at the call site!
  """
  ```

**Comment by KupiaSecAdmin** [comment]
@rickkk137 - Thanks for your comment. You are absolutely correct that the protocol tries to balance two tokens when burning, but still, it allows imbalanced deposit. You can think of the following scenario:

- It's BTC bullish period, people usually want to keep BTC, and they deposit BTC into Verla not only to have BTC price increased but also to get fees from their assets.
- This can cause as huge imbalance as possible between BTC and USDC assets.
- Since it's BTC bullish, there will be relatively much more long openers and short openers.
- As a result, because of the described issue, the Verla protocol ends up with assets being drained because of inverse mechanism of funding fees.

**Comment by WangSecurity** [comment]
After additional re-checks, this is indeed how the protocol decides to calculate the funding fees. These are not losses of funds, since it's how the fees are intended to be calculated. I agree it's not the most efficient way and other designs would be more optimal, but this is only a recommendation to use a more fair formula. Planning to reject the escalation and leave the issue as it is.

**Comment by KupiaSecAdmin** [comment]
@WangSecurity - This is not only the recommendation, this funding fee design has significant mistake, and it will cause significant protocol loss for LPs and the protocol.

It's basic concept of perpetual trading that long position openers pay funding fees when the price of underlying assets go up, but Verla works in the opposite way. There is no single protocol that calculates funding fees in this way.

**Comment by WangSecurity** [comment]
The way how other protocols or perpetual exchanges work doesn't mean that every protocol has to work in that manner. Verla protocol chose specifically this design of calculating funding. Hence, it's not a loss of funds, but how the protocol is intended to work. The decision remains the same, reject the escalation and leave the issue as it is.

**Comment by KupiaSecAdmin** [comment]
@WangSecurity - When a protocol has chosen a wrong design that causes consistent losses for their liquidity providers, should it be considered "intended"?

The liquidity providers in Verla protocol will just end up losing their LPs provided to Verla protocol because of the incorrect funding fee logic.

**Comment by KupiaSecAdmin** [comment]
Let me add some more facts for better understanding.

Basically, let's think of a perpetual world where funding fee does not exist. When it comes to bullish period, 100% traders understand that BTC price will go up for specific period, which means all traders will try to open LONG positions with MAX leverage, it's simple because there is no loss for traders and traders want to maximize the profit. While this gives all traders maximum profit, it means significant loss for the protocol(or liquidity providers) on the other hand.

Here comes the funding fee to prevent traders from opening LONG positions without caring about any risk. The funding fee incentivizes some traders to open SHORT positions even in bullish period, because based on the balance between LONG and SHORT positions, they can get profit from funding fee while they lose their BTC on the other hand, totally netting profit.

Now, let's think of how Verla protocol works. It determines the party that pays funding fee based on the utilization ratio, not based on price movement. So, as long as the pools are imbalanced, there will be times where LONG position traders not only maximize their profit from leverage but also they even receive funding fees from SHORT position traders. In a word, there's no risk at all for opening LONG positions, which on the other hand means significant loss for liquidity providers.

Also, once LONG position traders open tons of positions, liquidity providers can't even withdraw their assets.

As a result, BTC on Verla protocol will get drained.

**Comment by WangSecurity** [comment]
I understand and agree on the part that it's not the best design, and there might be a better implementation. But, still, this is the design decision, some protocols decide to calculate fees in X way, others calculate in Y way, and Velar decides to calculate fees in this design. Hence, as I've said before, it's not a loss of funds, but how the protocol is intended to function and distribute the fees. 

Hence, the decision remains the same: reject the escalation and leave the issue as it is because it's intended to distribute fees in this way, and this is a design recommendation rather than a security issue.

**Comment by KupiaSecAdmin** [comment]
@WangSecurity - "Some protocols decide to calculate fees in X way, others calculate in Y way, and Velar decides to calculate fees in this design", even though whatever design they choose, there should not be a flaw in the design that causes loss of funds. I am not saying protocols must follow same design for funding fees calculation but my point is that the flaw in current design causes loss of funds for liquidity providers.

In addition, the role of "funding fees" in perp trading, it's not just normal fee like swap fee but it plays crucial role to prevent all traders opening LONG(or SHORT).

This issue should be valid indeed and severity should be high.

**Comment by WangSecurity** [comment]
But the current design doesn't have the flaw. The issue is not about the funding fees should be calculated in a certain way, but there's an error in the code that prevents the fees from being calculated as they should. Here, the fees are calculated as intended, even though it's suboptimal and allows for the situations as in the report. But, there's no error in the calculation (at least it's not shown in the report) and it's calculated as it should be.

Planning to reject the escalation and leave the issue as it is.

**Comment by KupiaSecAdmin** [comment]
I think there has been some confusion here, let me re-convince with some facts.

**Current Design**: The party that pays funding fees is determined by utilization ratio between BTC and USDT.
**The Flaw of the Design**: Allowing one-sided collateral deposit + current funding fee logic allows draining protocol assets because of imbalance between BTC and USDT assets. If pool was balanced, having utilization ratio as calculation mechanism is just fine.

**Assumption**: It's a BTC bullish period and Verla has imbalance between BTC and USDT, say 200 BTC($10m value) + 1M USDT($1m value).

**Why Verla Protocol Get Drained**

- By nature, every single trader(including all bots) look for an opportunity to open long BTC positions on DEX and CEX with as maximum leverage as they can have.
- The only reason that prevents them from opening long BTC positions is funding fees that could grow bigger than their profits.
- At this point, all DEX and CEX except Verla lets long position creators to pay funding fees for short position creators.
- The traders(including arbitrage bots) that were not able to open positions in other DEX and CEX just open positions in Verla. For example they open short positions in other perp protocol and long position in DEX.
- This allows traders(including arbitrage bots) to have non-negative profits, it's non-losing game for them.
- On the other hand, since short positions are open in other DEX and CEX, it balances traders there, but in Verla protocol, it's  draining of assets from the pool, because there's huge incentive for long position creators and no incentive for short position creators.

Not sure if I described the issue in a convincing way but whatever decision is made here, I will leave it up to @WangSecurity.

**Comment by WangSecurity** [comment]
The report doesn't show how the protocol could get drained. The report only shows a scenario where shorts would unfairly pay the funding fees due to utilisation, which, as I've explained before, is intended. Hence, the report doesn't show medium severity and the scenario where the protocol gets drained. 
Hence, the report has to remain invalid.

**Comment by KupiaSecAdmin** [comment]
Not sure about the better way to describe the issue, I will just accept the decision of HoJ.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [KupiaSecAdmin](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/76/#issuecomment-2344251158): rejected
