### ISSUE TITLE
bughuntoor - Current slippage protection forces transaction to revert if price is too good.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-velar-artha-judging#84]
bughuntoor

High

# Current slippage protection forces transaction to revert if price is too good.

## Summary
Current slippage protection forces transaction to revert if price is too good.

## Vulnerability Detail
When the user wishes to open a position, they specify a desired price and the max slippage they're willing to accept.
The current implementation is that if the delta of the desired price and the actual price is more than the max slippage, the transaction reverts

```vyper
def check_slippage(current: uint256, desired: uint256, slippage: uint256) -> bool:
  if current > desired: return (current - desired) <= slippage
  else                : return (desired - current) <= slippage
```

The problem is that this doesn't take into account the situation where the price has moved more than slippage in the right direction for the user.
For example, if the user wishes to open a long with desired price $1 and max slippage they've set is $0.10 and price drops to $0.8, current implementation would revert, although it shouldn't - user would only benefit if they could open their long position at a lower price. 

Same thing for shorts if the price has increased prior to opening the position.

This is basically the equivalent of a swap transaction failing due to receiving more tokens than specified.

## Impact
DoS, loss of funds

## Code Snippet
https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/oracle.vy#L122

## Tool used

Manual Review

## Recommendation
Depending on whether the position is long or short, check for price movements only in certain direction

**Comment by spacegliderrrr** [comment]
Escalate

Issue should be validated. It correctly showcases a situation where users will be unable to open a position, in a situation where they usually would be able to. Given that opening a position is a time sensitive operation, issue should be Medium severity.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Issue should be validated. It correctly showcases a situation where users will be unable to open a position, in a situation where they usually would be able to. Given that opening a position is a time sensitive operation, issue should be Medium severity.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by msheikhattari** [comment]
This was correctly invalidated, user has specified a desired price and slippage is correctly how far from that price he could tolerate a deviation. This is a valid design choice.

**Comment by WangSecurity** [comment]
Yeah, I agree with the above comment. The fact that there's slippage for both sides (i.e. for price moving both up and down) is not an issue by itself, and since the price is indeed outside of the range set by the user, I believe this has to remain invalid. Please correct me if it's wrong, planning to reject the escalation.

**Comment by spacegliderrrr** [comment]
I disagree with comment above. Situation is the same as with swaps - if you've set slippage and price moves right before the swap and gives you more tokens than expected, it doesn't make sense for it to revert (and it doesn't).

Especially for 1X leverage trades (which are ultimately the same as swaps) where the payout is ALWAYS* the same (not accounting for fees, but they're not important in this case). Reverting on better price, directly means losing on money for no reason.

*the payouts are always the same, as they're in the target token - when you're opening a long, you're essentially buying the base token. For example, if you open a $50k BTC long at price $50k, even if you close it at $70k, or at $30k, protocol will always payout in BTC and will therefore always pay you 1 BTC upon closing.

In the current implementation, if you wanted to open that same $50k BTC long position but price moved to $45k, it would revert, although it should usually give you 1.1 BTC, instead of the just 1 BTC you initially signed up for.

**Comment by WangSecurity** [comment]
I agree with the fact that it would make the code and UX better, but it's a completely viable design. Yeah, usually, slippage is set only on one side, but that doesn't necessarily mean Velar has to use the same design and not apply slippage for "good" price changes. This is the specific design of the slippage and how it should work in this protocol. Hence, my decision remains: this is only a design recommendation not to apply the slippage when the price moves in your favour, reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [spacegliderrrr](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/84/#issuecomment-2344513720): rejected
