### ISSUE TITLE
bughuntoor - Liquidity providers can remove liquidity to force positions into high fees

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-velar-artha-judging#88]
bughuntoor

Medium

# Liquidity providers can remove liquidity to force positions into high fees

## Summary
Liquidity providers can remove liquidity to force positions into high fees

## Vulnerability Detail
Within the protocol, position fees are based on utilization of the total LP amount.
```vyper
def dynamic_fees(pool: PoolState) -> DynFees:
    long_utilization : uint256 = self.utilization(pool.base_reserves, pool.base_interest)
    short_utilization: uint256 = self.utilization(pool.quote_reserves, pool.quote_interest)
    borrowing_long   : uint256 = self.check_fee(
      self.scale(self.PARAMS.MAX_FEE, long_utilization))
    borrowing_short  : uint256 = self.check_fee(
      self.scale(self.PARAMS.MAX_FEE, short_utilization))
    funding_long     : uint256 = self.funding_fee(
      borrowing_long, long_utilization,  short_utilization)
    funding_short    : uint256 = self.funding_fee(
      borrowing_short, short_utilization,  long_utilization)
    return DynFees({
        borrowing_long : borrowing_long,
        borrowing_short: borrowing_short,
        funding_long   : funding_long,
        funding_short  : funding_short,
    })
```
The problem is that this number is dynamic and LP providers can abuse it at any point

Consider the following scenario:
1. There's a lot of liquidity in the pool
2. User opens a position for a fraction of it, expecting low fees due the low utilization
3. LP providers withdraw most of liquidity, forcing high utilization ratio and ultimately high fees.

## Impact
Loss of funds

## Code Snippet
https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/params.vy#L33

## Tool used

Manual Review

## Recommendation
Consider using a different way to calculate fees which is not manipulatable by the LP providers.

Duplicate of #89

**Comment by msheikhattari** [comment]
Escalate
This is a duplicate of #89 which is invalid - the issue is describing the same exact functionality regarding LPs manipulating the utilization to skew fee calculations.

This attack is even less likely to occur than the one described in #89. Not only will the high fees drive positions out & LPs in (driving fees back down), the whale has 0 incentive to do this as he is not receiving any of the elevated fees...

**Comment by sherlock-admin3** [comment]
> Escalate
> This is a duplicate of #89 which is invalid - the issue is describing the same exact functionality regarding LPs manipulating the utilization to skew fee calculations.
> 
> This attack is even less likely to occur than the one described in #89. Not only will the high fees drive positions out & LPs in (driving fees back down), the whale has 0 incentive to do this as he is not receiving any of the elevated fees...

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
@spacegliderrrr do you have any counterarguments?

**Comment by spacegliderrrr** [comment]
> This attack is even less likely to occur than the one described in https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/89. Not only will the high fees drive positions out & LPs in (driving fees back down), the whale has 0 incentive to do this as he is not receiving any of the elevated fees...

If the whale holds majority of the LP and after removing continues to hold the majority, they'll get most of the extra fees. However I do agree that this is much less likely than the issue described in #89.

**Comment by WangSecurity** [comment]
Another question, the whale LP can withdraw funds only up to the borrowed amount for trading, i.e. if the pool has 50k tokens and the traders use 40k of that pool, the attacker can withdraw only 10k, correct?

**Comment by WangSecurity** [comment]
Bumping up @spacegliderrrr and @msheikhattari

**Comment by spacegliderrrr** [comment]
@WangSecurity Yes, correct.

**Comment by WangSecurity** [comment]
I see how this is similar to #89 cause in both scenarios LP causes high fees, but they stem from different factors:
1. Here the LP withdraws liquidity from the pool, increasing the utilisation.
2. In #89, the LP opens new positions, increasing the utilisation.

While they lead to similar impacts, they come from the different cause. Hence, I see them as non-duplicates.

About the validity/severity. Indeed, this scenario is riskier, but still, it shows how the LP could cause short-term losses to LP traders and even drive their positions out. With that, this issue is sufficient for Medium severity. Planning to reject the escalation and leave the issue as it is.

**Comment by Tobi0x18** [comment]
@WangSecurity
Thanks for your judging.
The method of calculating fees of the protocol is indeed unusual.
However, I believe that the reports [#88](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/88) and [#89](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/89) share the same root cause, which stems from improper logic in the fee calculation.

Both reports suggest increasing the fees by raising the utilization ratio. 
Specifically :
- [#88](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/88) indicates that the utilization ratio can be increased by whale liquidity providers removing liquidity from the pool : decreasing denominator
- [#89](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/89) suggests that it can be increased by whale liquidity providers opening positions in both directions : increasing numerator

I agree with the severity of these issues but I think this should be merged as one.

**Comment by pashap9990** [comment]
When liquidity is removed, [the pool automatically rebalances using the burn function](https://github.com/sherlock-audit/2024-08-velar-artha/blob/18ef2d8dc0162aca79bd71710f08a3c18c94a36e/gl-sherlock/contracts/math.vy#L127), meaning LPs cannot choose which asset they withdraw. The withdrawal depends on the pool's reserves. The balanced function adjusts the withdrawn mix to restore balance, aiming for equal value in base and quote reserves.

Additionally, when liquidity is removed, a new fee rate applies for the current block users can close their positions and pay fee base on past fee rate in result open interest will be decreased and fee rate will be decreased. If a large amount is withdrawn, the LP's share of the pool decreases, and they earn fewer fees. The higher fee rate encourages other LPs to deposit, which then lowers the rate again and imo this is intended design and I don't see any problem here but I agree #89 is valid because users shouldn't been allowed to position in both side

Not that,user open a position in block 1 and fee rate is 1 and after 100 blocks LPs remove their liquidity and fee rate become 2 and user closes his pisition in block 102 
Fee = 1 * 100 + 2 × 2

**Comment by WangSecurity** [comment]
Thank you for both of these comments, but as I understand, it's still possible for the LP to "sky-rocket" the funding fees due to withdrawing and making the utilisation very high, causing losses of fees. Hence, I would still say it's valid issue.

About it being a duplicate, I see the point. Indeed, both issues stem from the funding fees being calculated based on the utilisation (root cause) but show different attack paths (how to increase the utilisation ratio). Hence, I agree they can be duplicated. The escalation will still be rejected, but the issue will be duplicated with #89. Plan to apply this decision tomorrow morning.

**Comment by WangSecurity** [comment]
Result:
Medium 
Duplicate of #89

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [msheikhattari](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/88/#issuecomment-2345023658): rejected
